cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
    path('success/', views.success, name="success"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.frontpage, name="home"),
    path('contact-us/', views.contactpage, name="contact"),
]

product/urls.py
from . import views
from django.urls import path



app_name = 'product'


urlpatterns = [
    path('search', views.search, name="search"),
    path('<slug:category_slug>/<slug:product_slug>/', views.product, name="product"),
    path('<slug:category_slug>/', views.category, name="category"),
    
]

simple_multivendor_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('vendor/', include('vendor.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from product.models import Product

# Create your views here.

def frontpage(request):
    newest_products = Product.objects.all()[0:8]
    context = {
        'newest_products': newest_products,
    }
    return render(request, 'core/frontpage.html', context)


def contactpage(request):
    return render(request, 'core/contact.html')

templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}Multi Vendor E-Commerce Website{% endblock title %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>

    <div class="container">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'core:home' %}">
                <img src="https://2.bp.blogspot.com/-mkVne3V2tzY/Xfo99c80KUI/AAAAAAAAD_c/9EbC4qu-fYAeVjLi3ONzRZ-osIW4H3qBACK4BGAYYCw/s1600/Vijay%2BThapa%2BLogo%2BHD.png" width="112" height="28">
                </a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                <a class="navbar-item" href="{% url 'core:home' %}">
                    Home
                </a>
                
                {% for category in categories %}
                    <a class="navbar-item" href="{% url 'product:category' category.slug %}">
                        {{category.title}}
                    </a>
                {% endfor %}

                

                </div>

                <div class="navbar-start">
                    <div class="navbar-item">
                        <form method="get" action="{% url 'product:search' %}">
                            <div class="field has-addons">
                                <div class="control">
                                    <input type="search" name="query" id="" class="input" placeholder="Search...">
                                </div>
                                <div class="control">
                                    <button class="button is-dark is-uppercase">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="navbar-end">

                <div class="navbar-item">
                    <a href="{% url 'cart:cart' %}" class="button is-warning">Cart {% if cart %}({{cart|length}}){% endif %}</a>
                </div>
                
                {% if request.user.is_authenticated %}

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-capitalized">
                    {{user.vendor.name}}
                    </a>

                    <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'vendor:vendor-admin' %}">
                        Profile
                    </a>
                    <a class="navbar-item" href="{% url 'vendor:edit-vendor' %}">
                        Update Profile
                    </a>
                    <a class="navbar-item" href="{% url 'vendor:add-product' %}">
                        Add Product
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'vendor:logout' %}">
                        Logout
                    </a>
                    </div>
                </div>

                {% else %}

                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'vendor:become-vendor' %}">
                            <strong>Become Vendor</strong>
                        </a>
                        <a class="button is-light" href="{% url 'vendor:login' %}">
                            Log in
                        </a>
                    </div>
                </div>

                {% endif %}


                </div>
            </div>
            </nav>
    </div>
    
    <section class="section">
        <div class="container">

            {% block content %}{% endblock content %}

        </div>
    </section>

    
    <footer class="footer">
        <div class="container">
            <h3 class="is-size-4 mb-4">Multi Vendor E-Commerce</h3>
            
            {% if request.user.is_authenticated %}
                <a href="{% url 'vendor:vendor-admin' %}">Vendor Admin</a>
            {% else %}
                <a href="{% url 'vendor:become-vendor' %}">Become a Vendor</a>
            {% endif %}

            <br>
            <a href="{% url 'vendor:vendors' %}">All Vendors</a>

        </div>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}

</body>
</html>

templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %}Contact Us{% endblock title %}

{% block content %}

    <h1>Contact Us</h1>

    

{% endblock content %}

templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Home Page{% endblock title %}

{% block content %}
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-test-centered mt-6 mb-6">
            <h2 class="is-size-3">Latest Products</h2>
        </div>

        {% for product in newest_products %}
            {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>
{% endblock content %}